### ISSUE TITLE
参数对象方式分页失败

### ISSUE THREAD

**Issue by 12monkey12** [pagehelper/pagehelper-spring-boot#133]
```
# 分页插件配置
pagehelper:
 helperDialect: mysql
  offset-as-page-num: true
  row-bounds-with-count: true
  page-size-zero: true
  reasonable: true
  support-methods-arguments: true
```

```
<dependency>
            <groupId>com.github.pagehelper</groupId>
            <artifactId>pagehelper-spring-boot-starter</artifactId>
            <version>1.4.1</version>
        </dependency>
<parent>
        <artifactId>spring-boot-starter-parent</artifactId>
        <groupId>org.springframework.boot</groupId>
        <version>2.3.1.RELEASE</version>
    </parent>
```

```
@SpringBootTest
@RunWith(SpringRunner.class)
public class PersonServiceTest {

    @Resource
    private BookMapper bookMapper;

    @Test
    public void testPageHelper(){
        PageHelper.startPage(1,2);
        List<Book> list = bookMapper.findAll();
        PageInfo pageInfo = new PageInfo(list);
        System.out.println(pageInfo);
    }

    @Test
    public void testPageParam(){
        List<Book> list = bookMapper.findAllByPageNumAndSize(1,2);
        PageInfo pageInfo = new PageInfo(list);
        System.out.println(pageInfo);
    }
}
```

- PageHelper.startPage(1,2); 方式分页成功，返回的是一个 Page 类型的对象
- findAllByPageNumAndSize(1,2); 方式分页失败，返回的是一个 ArrayList 类型的对象
