### ISSUE TITLE
使用yaml配置启动发生ClassCastException错误

### ISSUE THREAD

**Issue by lishifeng0** [pagehelper/pagehelper-spring-boot#25]
项目使用spring boot 1.5.7，application.yml中的pagehelper配置如下时
```yaml
pagehelper:
  auto-dialect: true
  close-conn: true
```
启动出现org.springframework.beans.factory.BeanCreationException: Error creating bean with name '**com.github.pagehelper.autoconfigure.PageHelperAutoConfiguration**': Invocation of init method failed; nested exception is **java.lang.ClassCastException**: java.lang.Boolean cannot be cast to java.lang.String。
苦苦思索查找几日，发现问题出在**PageHelperProperties**类中。
现在我的折中做法是
```yaml
pagehelper:
  auto-dialect: !!str true
  close-conn: !!str true
```
但还请作者稍稍处理一下这个问题。
