### ISSUE TITLE
不支持参数方式的page对象？

### ISSUE THREAD

**Issue by Dreampie** [pagehelper/pagehelper-spring-boot#3]
```yml
pagehelper:
  helperDialect: mysql
  reasonable: true
  rowBoundsWithCount: true

```
```java
@Select("<script>SELECT * FROM alc_city WHERE " +
            "<if test='#{city.id} != null'>id = #{city.id} AND </if>" +
            "deleted_at is null</script>")
    Page<CityEntity> find(@Param("city") CityEntity city, PageRowBounds page);
```

```java
@Test
    public void find() throws Exception {
        PageRowBounds pageRowBounds = new PageRowBounds(0, 10);
        List<CityEntity> cityEntities = cityMapper.find(new CityEntity(), pageRowBounds);
        // 日志打印的 total是1，对象里面确实0，列表也没有值为什么？
        Assert.assertTrue(cityEntities.size() > 0);
    }
```
